(ns kixi.ifore-schema
  (:require [schema.core :as s]
            [clojure.tools.logging :as log]))

(def IforeHeader
  [(s/one (s/eq "Wattbox Build ID") "Wattbox Build ID")
   (s/one (s/eq "Date Time") "Date Time")
   s/Str])

(def IforeFields
  {"Wattbox Build ID" (s/one s/Str "Wattbox Build ID")
   "Date Time" (s/one s/Str "Date Time")
   "K" (s/one s/Str "K")
   "Relay Command" (s/one s/Str "Relay Command")
   "Tank Heated Volume" (s/one s/Str "Tank Heated Volume")
   "Prestart Time" (s/one s/Str "Prestart Time")
   "BooOccupantPresent" (s/one s/Str "BooOccupantPresent")
   "Temp Profile Selected" (s/one s/Str "Temp Profile Selected")
   "Temp SetPoint" (s/one s/Str "Temp SetPoint")
   "More Heat Button Push" (s/one s/Str "More Heat Button Push")
   "More Heat Profile Adjust" (s/one s/Str "More Heat Profile Adjust")
   "Less Heat Button Push" (s/one s/Str "Less Heat Button Push")
   "Less Heat Profile Adjust" (s/one s/Str "Less Heat Profile Adjust")
   "Hot Water Button Push" (s/one s/Str "Hot Water Button Push")
   "Hot Water Activated" (s/one s/Str "Hot Water Activated")
   "ControllingRoom_Temp" (s/one s/Str "ControllingRoom_Temp")
   "External_Temp" (s/one s/Str "External_Temp")
   "External_Humidity" (s/one s/Str "External_Humidity")
   "TankBody_Temp" (s/one s/Str "TankBody_Temp")
   "TankBase_Temp" (s/one s/Str "TankBase_Temp")
   "LoungeA_Temp" (s/one s/Str "LoungeA_Temp")
   "LoungeA_Humidity" (s/one s/Str "LoungeA_Humidity")
   "LoungeB_Temp" (s/one s/Str "LoungeB_Temp")
   "LoungeB_CO2" (s/one s/Str "LoungeB_CO2")
   "Bedroom1_Temp" (s/one s/Str "Bedroom1_Temp")
   "Bedroom1_Humidity" (s/one s/Str "Bedroom1_Humidity")
   "KitchenA_Temp" (s/one s/Str "KitchenA_Temp")
   "KitchenA_Humidity" (s/one s/Str "KitchenA_Humidity")
   "ElecLoadforWattBox" (s/one s/Str "ElecLoadforWattBox")
   "ElecMeterPulse" (s/one s/Str "ElecMeterPulse")
   "GasMeterPulse" (s/one s/Str "GasMeterPulse")
   "" (s/optional s/Str "Trailing Data")})

(def Ifore
  (s/either LongIfore ShortIfore))

(defn validator [header]
  (s/validate IforeHeader header)
  (let [v (into [] (map #(get IforeFields %) header))]
    (log/debugf "Using validator: %s with header: header: %s" (s/explain v) header)
    v))

(comment

  ;; Examples of IFORE formatted files

  (def LongIfore
    [(s/one s/Str "Wattbox Build ID")
     (s/one s/Str "Date Time")
     (s/one s/Str "K")
     (s/one s/Str "Relay Command")
     (s/one s/Str "Tank Heated Volume")
     (s/one s/Str "Prestart Time")
     (s/one s/Str "BooOccupantPresent")
     (s/one s/Str "Temp Profile Selected")
     (s/one s/Str "Temp SetPoint")
     (s/one s/Str "More Heat Button Push")
     (s/one s/Str "More Heat Profile Adjust")
     (s/one s/Str "Less Heat Button Push")
     (s/one s/Str "Less Heat Profile Adjust")
     (s/one s/Str "Hot Water Button Push")
     (s/one s/Str "Hot Water Activated")
     (s/one s/Str "ControllingRoom_Temp")
     (s/one s/Str "External_Temp")
     (s/one s/Str "External_Humidity")
     (s/one s/Str "TankBody_Temp")
     (s/one s/Str "TankBase_Temp")
     (s/one s/Str "LoungeA_Temp")
     (s/one s/Str "LoungeA_Humidity")
     (s/one s/Str "LoungeB_Temp")
     (s/one s/Str "LoungeB_CO2")
     (s/one s/Str "Bedroom1_Temp")
     (s/one s/Str "Bedroom1_Humidity")
     (s/one s/Str "KitchenA_Temp")
     (s/one s/Str "KitchenA_Humidity")
     (s/one s/Str "ElecLoadforWattBox")
     (s/one s/Str "ElecMeterPulse")
     (s/one s/Str "GasMeterPulse")
     (s/optional s/Str "Trailing Data")])


  (def ShortIfore
    [(s/one s/Str "Wattbox Build ID")
     (s/one s/Str "Date Time")
     (s/one s/Str "K")
     (s/one s/Str "Relay Command")
     (s/one s/Str "Tank Heated Volume")
     (s/one s/Str "Prestart Time")
     (s/one s/Str "BooOccupantPresent")
     (s/one s/Str "Temp Profile Selected")
     (s/one s/Str "Temp SetPoint")
     (s/one s/Str "More Heat Button Push")
     (s/one s/Str "More Heat Profile Adjust")
     (s/one s/Str "Less Heat Button Push")
     (s/one s/Str "Less Heat Profile Adjust")
     (s/one s/Str "Hot Water Button Push")
     (s/one s/Str "Hot Water Activated")
     (s/one s/Str "ControllingRoom_Temp")
     (s/one s/Str "External_Temp")
     (s/one s/Str "External_Humidity")
     (s/one s/Str "LoungeA_Temp")
     (s/one s/Str "LoungeA_Humidity")
     (s/one s/Str "LoungeB_Temp")
     (s/one s/Str "LoungeB_CO2")
     (s/one s/Str "Bedroom1_Temp")
     (s/one s/Str "Bedroom1_Humidity")
     (s/one s/Str "KitchenA_Temp")
     (s/one s/Str "KitchenA_Humidity")
     (s/one s/Str "ElecLoadforWattBox")
     (s/one s/Str "ElecMeterPulse")
     (s/one s/Str "GasMeterPulse")
     (s/optional s/Str "Trailing Data")])
  )
